# https://circleci.com/docs/2.0/language-javascript/
version: 2
jobs:
  'node-12':
    docker:
      - image: circleci/node:16
        environment:
          DATABASE_URL: postgres://test:test@localhost:5432/test
          ROOT_DATABASE_URL: postgres://test:test@localhost:5432/test
          SHADOW_DATABASE_URL: postgres://test:test@localhost:5432/test_shadow
      - image: postgres:12
        environment:
          POSTGRES_PASSWORD: test
          POSTGRES_USER: test
          POSTGRES_DB: test
    working_directory: ~/ra-pg
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn test
      - run: yarn run cov:send
  'node-latest':
    docker:
      - image: circleci/node:latest
        environment:
          DATABASE_URL: postgres://test:test@localhost:5432/test
          ROOT_DATABASE_URL: postgres://test:test@localhost:5432/test
          SHADOW_DATABASE_URL: postgres://test:test@localhost:5432/test_shadow
      - image: postgres:12
        environment:
          POSTGRES_PASSWORD: test
          POSTGRES_USER: test
          POSTGRES_DB: test
    working_directory: ~/ra-pg
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn test
      - run: yarn run cov:send
  publish:
    docker:
      - image: circleci/node:16
    working_directory: ~/ra-pg
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn semantic-release
      - run: yarn doc:html && yarn doc:json
      - run: git config user.email "david@vexquisit.com"
      - run: git config user.name "ci-build"
      - add_ssh_keys:
          fingerprints:
            - '5d:16:ea:3a:5c:18:b9:b7:04:80:99:35:81:09:d9:e4'
      - run: yarn doc:publish

workflows:
  version: 2
  build:
    jobs:
      - 'node-12'
      - 'node-latest'
      - publish:
          filters:
            branches:
              only:
                - master
                - beta
                - next
          requires:
            - 'node-12'
            - 'node-latest'
